### ISSUE TITLE
PyTorch NCCL Fails on GH200 `aarch64`

### ISSUE THREAD

**Issue by wahabk** [conda-forge/pytorch-cpu-feedstock#297]
### Solution to issue cannot be found in the documentation.

- [x] I checked the documentation.

### Issue

Hello, thank you for supporting `aarch64` with conda-forge!

Unfortunately, the NCCL (Version 2.23.4) built for this PyTorch fails on our GH200 HPE Slingshot cluster. NCCL requires the use of our own provided `libfabric` and NCCL Plugin (https://github.com/aws/aws-ofi-nccl). PyTorch statically links to NCCL so while I cannot modify the NCCL used I can add the plugin without rebuilding from source.

I installed this conda env file:

```yaml
name: pytorch_env
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python=3.10
  - pytorch=2.5.1
  - torchvision
  - transformers
```

# Replicate

I tried to execute a 2 node benchmark with the NCCL backend. However, it fails:

```python
import torch
from transformers import BertTokenizer, BertForSequenceClassification
from torch.nn.parallel import DistributedDataParallel as DDP
import torch.distributed as dist
import time
import os

def init_process(backend='nccl'): # change to 'nccl' to use NCCL backend
    dist.init_process_group(backend=backend) 
    torch.cuda.set_device(int(os.environ['LOCAL_RANK']))

    if dist.get_rank() == 0:
        print(f"Initializing process group with backend: {backend}")
        num_cuda_devices = torch.cuda.device_count()
        print(f"Number of available CUDA devices: {num_cuda_devices}")
        world_size = dist.get_world_size()
        print(f"World size (number of processes in the process group): {world_size}")


def benchmark():
    # Load pre-trained model and tokenizer
    model_name = "bert-base-uncased"
    tokenizer = BertTokenizer.from_pretrained(model_name)
    model = BertForSequenceClassification.from_pretrained(model_name).cuda()
    model = DDP(model, device_ids=[int(os.environ['LOCAL_RANK'])])

    # Prepare some sample text and labels
    texts = ["This is a sample sentence for benchmarking BERT."] * 32  # Batch of 32 sentences
    inputs = tokenizer(texts, return_tensors="pt", padding=True, truncation=True).to('cuda')
    labels = torch.ones(32, dtype=torch.long).to('cuda')  # Dummy labels

    # Benchmarking
    start_time = time.time()

    # Forward pass
    outputs = model(**inputs, labels=labels)
    loss = outputs.loss

    # Backward pass
    loss.backward()

    end_time = time.time()

    if dist.get_rank() == 0:
        print(f"Time taken for one forward and backward pass: {end_time - start_time} seconds")
    dist.destroy_process_group()

if __name__ == "__main__":
    init_process()
    benchmark()
```

# Error

I have run this with `NCCL_DEBUG=INFO` and I haven't seen any other errors or warnings. It looks like the tree rings are connected fine but the sys call is failing.

```shell
[E1203 11:52:35.150201497 ProcessGroupNCCL.cpp:542] [Rank 6] Collective WorkNCCL(SeqNum=7, OpType=ALLREDUCE, NumelIn=109483778, NumelOut=109483778, Timeout(ms)=600000) raised the following async exception: NCCL error: unhandled system error (run with NCCL_DEBUG=INFO for details), NCCL version 2.23.4

ncclSystemError: System call (e.g. socket, malloc) or external library call failed or device error. 
Last error:

Exception raised from checkForNCCLErrorsInternal at /home/conda/feedstock_root/build_artifacts/libtorch_1733169137697/work/torch/csrc/distributed/c10d/ProcessGroupNCCL.cpp:2027 (most recent call first):
frame #0: c10::Error::Error(c10::SourceLocation, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >) + 0xe8 (0xffff380ca2a8 in /home/brics/akawafi1.brics/miniforge3/envs/pytorch_env/lib/python3.10/site-packages/torch/../../.././libc10.so)
frame #1: <unknown function> + 0x14407b8 (0xffff395507b8 in /home/brics/akawafi1.brics/miniforge3/envs/pytorch_env/lib/python3.10/site-packages/torch/../../.././libtorch_cuda.so)
frame #2: c10d::ProcessGroupNCCL::checkForNCCLErrorsInternal(std::shared_ptr<c10d::NCCLComm>&) + 0x2a0 (0xffff3959adf0 in /home/brics/akawafi1.brics/miniforge3/envs/pytorch_env/lib/python3.10/site-packages/torch/../../.././libtorch_cuda.so)
frame #3: c10d::ProcessGroupNCCL::WorkNCCL::checkAndSetException() + 0xc4 (0xffff3959b114 in /home/brics/akawafi1.brics/miniforge3/envs/pytorch_env/lib/python3.10/site-packages/torch/../../.././libtorch_cuda.so)
frame #4: c10d::ProcessGroupNCCL::WorkNCCL::isCompleted() + 0xe8 (0xffff3959b598 in /home/brics/akawafi1.brics/miniforge3/envs/pytorch_env/lib/python3.10/site-packages/torch/../../.././libtorch_cuda.so)
frame #5: c10d::ProcessGroupNCCL::watchdogHandler() + 0x24c (0xffff3959c3dc in /home/brics/akawafi1.brics/miniforge3/envs/pytorch_env/lib/python3.10/site-packages/torch/../../.././libtorch_cuda.so)
frame #6: c10d::ProcessGroupNCCL::ncclCommWatchdog() + 0x178 (0xffff3959ddf8 in /home/brics/akawafi1.brics/miniforge3/envs/pytorch_env/lib/python3.10/site-packages/torch/../../.././libtorch_cuda.so)
frame #7: <unknown function> + 0xd600c (0xffff37ee600c in /home/brics/akawafi1.brics/miniforge3/envs/pytorch_env/lib/python3.10/site-packages/torch/../../.././libstdc++.so.6)
frame #8: <unknown function> + 0x875c (0xffff9740875c in /lib64/libpthread.so.0)
frame #9: <unknown function> + 0xdfeec (0xffff9722feec in /lib64/libc.so.6)

nid001016:96223:96628 [1] NCCL INFO comm 0xaaab0798fb90 rank 1 nranks 8 cudaDev 1 busId 1901000 - Abort COMPLETE
nid001017:124594:125023 [1] NCCL INFO comm 0xaaab0c6ef230 rank 5 nranks 8 cudaDev 1 busId 1901000 - Abort COMPLETE
```

### Installed packages

```shell
# packages in environment at /home/brics/akawafi1.brics/miniforge3/envs/pytorch_env:
#
# Name                    Version                   Build  Channel
_openmp_mutex             4.5                       2_gnu    conda-forge
aiohappyeyeballs          2.4.4              pyhd8ed1ab_0    conda-forge
aiohttp                   3.11.9          py310heeae437_0    conda-forge
aiosignal                 1.3.1              pyhd8ed1ab_0    conda-forge
async-timeout             5.0.1              pyhd8ed1ab_0    conda-forge
attr                      2.5.1                h4e544f5_1    conda-forge
attrs                     24.2.0             pyh71513ae_0    conda-forge
aws-c-auth                0.8.0               hac900a4_10    conda-forge
aws-c-cal                 0.8.0                h35473ba_2    conda-forge
aws-c-common              0.10.3               h86ecc28_0    conda-forge
aws-c-compression         0.3.0                h4c7db1d_2    conda-forge
aws-c-event-stream        0.5.0                h9bacb8c_7    conda-forge
aws-c-http                0.9.1                hf4e072c_2    conda-forge
aws-c-io                  0.15.2               h10eb1bc_2    conda-forge
aws-c-mqtt                0.11.0               h28a5e6a_8    conda-forge
aws-c-s3                  0.7.3                h29aef15_0    conda-forge
aws-c-sdkutils            0.2.1                h4c7db1d_1    conda-forge
aws-checksums             0.2.2                h4c7db1d_1    conda-forge
aws-crt-cpp               0.29.6               h7939e66_1    conda-forge
aws-sdk-cpp               1.11.449             h7085e57_4    conda-forge
azure-core-cpp            1.14.0               h1887c18_0    conda-forge
azure-identity-cpp        1.10.0               h47b0b28_0    conda-forge
azure-storage-blobs-cpp   12.13.0              h185ecfd_1    conda-forge
azure-storage-common-cpp  12.8.0               h1b94036_1    conda-forge
azure-storage-files-datalake-cpp 12.12.0              h37d6d07_1    conda-forge
brotli-python             1.1.0           py310he30c3ed_2    conda-forge
bzip2                     1.0.8                h68df207_7    conda-forge
c-ares                    1.34.3               h86ecc28_1    conda-forge
ca-certificates           2024.8.30            hcefe29a_0    conda-forge
certifi                   2024.8.30          pyhd8ed1ab_0    conda-forge
cffi                      1.17.1          py310h1451162_0    conda-forge
charset-normalizer        3.4.0              pyhd8ed1ab_1    conda-forge
colorama                  0.4.6              pyhd8ed1ab_1    conda-forge
cpython                   3.10.15         py310hd8ed1ab_2    conda-forge
cuda-cudart               12.6.77              h3ae8b8a_0    conda-forge
cuda-cudart_linux-aarch64 12.6.77              h3ae8b8a_0    conda-forge
cuda-nvrtc                12.6.85              h5101a13_0    conda-forge
cuda-nvtx                 12.6.77              h5101a13_0    conda-forge
cuda-version              12.6                 h7480c83_3    conda-forge
cudnn                     9.3.0.75             h125f736_1    conda-forge
datasets                  3.1.0              pyhff2d567_0    conda-forge
dill                      0.3.8              pyhd8ed1ab_0    conda-forge
filelock                  3.16.1             pyhd8ed1ab_0    conda-forge
freetype                  2.12.1               hf0a5ef3_2    conda-forge
frozenlist                1.5.0           py310ha766c32_0    conda-forge
fsspec                    2024.9.0           pyhff2d567_0    conda-forge
gflags                    2.2.2             h5ad3122_1005    conda-forge
giflib                    5.2.2                h31becfc_0    conda-forge
glog                      0.7.1                h468a4a4_0    conda-forge
gmp                       6.3.0                h0a1ffab_2    conda-forge
gmpy2                     2.1.5           py310h615e639_2    conda-forge
h2                        4.1.0              pyhd8ed1ab_0    conda-forge
hpack                     4.0.0              pyh9f0ad1d_0    conda-forge
huggingface_hub           0.26.3             pyhd8ed1ab_0    conda-forge
hyperframe                6.0.1              pyhd8ed1ab_0    conda-forge
icu                       75.1                 hf9b3779_0    conda-forge
idna                      3.10               pyhd8ed1ab_1    conda-forge
jinja2                    3.1.4              pyhd8ed1ab_1    conda-forge
keyutils                  1.6.1                h4e544f5_0    conda-forge
krb5                      1.21.3               h50a48e9_0    conda-forge
lcms2                     2.16                 h922389a_0    conda-forge
ld_impl_linux-aarch64     2.43                 h80caac9_2    conda-forge
lerc                      4.0.0                h4de3ea5_0    conda-forge
libabseil                 20240722.0      cxx17_h5ad3122_1    conda-forge
libarrow                  18.1.0          hde2a89e_2_cuda    conda-forge
libarrow-acero            18.1.0          hfe4b40e_2_cuda    conda-forge
libarrow-dataset          18.1.0          hfe4b40e_2_cuda    conda-forge
libarrow-substrait        18.1.0          ha84c9a3_2_cuda    conda-forge
libblas                   3.9.0           25_linuxaarch64_openblas    conda-forge
libbrotlicommon           1.1.0                h86ecc28_2    conda-forge
libbrotlidec              1.1.0                h86ecc28_2    conda-forge
libbrotlienc              1.1.0                h86ecc28_2    conda-forge
libcap                    2.69                 h883460d_0    conda-forge
libcblas                  3.9.0           25_linuxaarch64_openblas    conda-forge
libcrc32c                 1.1.2                h01db608_0    conda-forge
libcublas                 12.6.4.1             h5101a13_0    conda-forge
libcufft                  11.3.0.4             h5101a13_0    conda-forge
libcufile                 1.11.1.6             h3d08a35_2    conda-forge
libcurand                 10.3.7.77            h5101a13_0    conda-forge
libcurl                   8.10.1               h3ec0cbf_0    conda-forge
libcusolver               11.7.1.2             h5101a13_0    conda-forge
libcusparse               12.5.4.2             h5101a13_0    conda-forge
libdeflate                1.22                 h86ecc28_0    conda-forge
libedit                   3.1.20191231         he28a2e2_2    conda-forge
libev                     4.33                 h31becfc_2    conda-forge
libevent                  2.1.12               h4ba1bb4_1    conda-forge
libffi                    3.4.2                h3557bc0_5    conda-forge
libgcc                    14.2.0               he277a41_1    conda-forge
libgcc-ng                 14.2.0               he9431aa_1    conda-forge
libgcrypt                 1.11.0               h8af1aa0_2    conda-forge
libgcrypt-devel           1.11.0               h86ecc28_2    conda-forge
libgcrypt-lib             1.11.0               h86ecc28_2    conda-forge
libgcrypt-tools           1.11.0               h86ecc28_2    conda-forge
libgfortran               14.2.0               he9431aa_1    conda-forge
libgfortran5              14.2.0               hb6113d0_1    conda-forge
libgomp                   14.2.0               he277a41_1    conda-forge
libgoogle-cloud           2.31.0               h3888205_0    conda-forge
libgoogle-cloud-storage   2.31.0               hb9b2b65_0    conda-forge
libgpg-error              1.51                 h05609ea_1    conda-forge
libgrpc                   1.67.1               h36c5df4_0    conda-forge
libiconv                  1.17                 h31becfc_2    conda-forge
libjpeg-turbo             3.0.0                h31becfc_1    conda-forge
liblapack                 3.9.0           25_linuxaarch64_openblas    conda-forge
libmagma                  2.8.0                hfc09aae_0    conda-forge
libmagma_sparse           2.8.0                hfc09aae_0    conda-forge
libnghttp2                1.64.0               hc8609a4_0    conda-forge
libnl                     3.11.0               h86ecc28_0    conda-forge
libnsl                    2.0.1                h31becfc_0    conda-forge
libnvjitlink              12.6.85              h5101a13_0    conda-forge
libnvjpeg                 12.3.3.54            h3ae8b8a_0    conda-forge
libopenblas               0.3.28          pthreads_h9d3fd7e_1    conda-forge
libparquet                18.1.0          hbf9e8bd_2_cuda    conda-forge
libpng                    1.6.44               hc4a20ef_0    conda-forge
libprotobuf               5.28.2               h029595c_0    conda-forge
libre2-11                 2024.07.02           h18dbdb1_1    conda-forge
libsqlite                 3.47.0               hc4a20ef_1    conda-forge
libssh2                   1.11.1               ha41c0db_0    conda-forge
libstdcxx                 14.2.0               h3f4de04_1    conda-forge
libstdcxx-ng              14.2.0               hf1166c9_1    conda-forge
libsystemd0               256.7                hd54d049_1    conda-forge
libthrift                 0.21.0               h154c74f_0    conda-forge
libtiff                   4.7.0                hec21d91_1    conda-forge
libtorch                  2.5.1           cuda126_hc461daa_205    conda-forge
libudev1                  256.7                h86ecc28_1    conda-forge
libutf8proc               2.9.0                h86ecc28_1    conda-forge
libuuid                   2.38.1               hb4cce97_0    conda-forge
libuv                     1.49.2               h86ecc28_0    conda-forge
libwebp-base              1.4.0                h31becfc_0    conda-forge
libxcb                    1.17.0               h262b8f6_0    conda-forge
libxcrypt                 4.4.36               h31becfc_1    conda-forge
libxml2                   2.13.5               hf4efe5d_0    conda-forge
libzlib                   1.3.1                h86ecc28_2    conda-forge
lz4-c                     1.9.4                hd600fc2_0    conda-forge
markupsafe                3.0.2           py310h66848f9_0    conda-forge
mpc                       1.3.1                h783934e_1    conda-forge
mpfr                      4.2.1                h2305555_3    conda-forge
mpmath                    1.3.0              pyhd8ed1ab_0    conda-forge
multidict                 6.1.0           py310heeae437_1    conda-forge
multiprocess              0.70.16         py310ha766c32_1    conda-forge
nccl                      2.23.4.1             h35f4307_3    conda-forge
ncurses                   6.5                  hcccb83c_1    conda-forge
networkx                  3.4.2              pyh267e887_2    conda-forge
nomkl                     1.0                  h5ca1d4c_0    conda-forge
numpy                     2.1.3           py310hed039d9_0    conda-forge
openjpeg                  2.5.2                h0d9d63b_0    conda-forge
openssl                   3.4.0                h86ecc28_0    conda-forge
orc                       2.0.3                h90de224_0    conda-forge
packaging                 24.2               pyhd8ed1ab_2    conda-forge
pandas                    2.2.3           py310hce852f7_1    conda-forge
pillow                    11.0.0          py310h825f53c_0    conda-forge
pip                       24.3.1             pyh8b19718_0    conda-forge
propcache                 0.2.0           py310ha766c32_2    conda-forge
pthread-stubs             0.4               h86ecc28_1002    conda-forge
pyarrow                   18.1.0          py310hbbe02a8_0    conda-forge
pyarrow-core              18.1.0          py310hc3911d1_0_cuda    conda-forge
pycparser                 2.22               pyh29332c3_1    conda-forge
pysocks                   1.7.1              pyha55dd90_7    conda-forge
python                    3.10.15         hbf90c55_2_cpython    conda-forge
python-dateutil           2.9.0.post0        pyhff2d567_1    conda-forge
python-tzdata             2024.2             pyhd8ed1ab_0    conda-forge
python-xxhash             3.5.0           py310h78583b1_1    conda-forge
python_abi                3.10                    5_cp310    conda-forge
pytorch                   2.5.1           cuda126_py310h11e4a38_205    conda-forge
pytz                      2024.1             pyhd8ed1ab_0    conda-forge
pyyaml                    6.0.2           py310ha766c32_1    conda-forge
rdma-core                 54.0                 h1d056c8_1    conda-forge
re2                       2024.07.02           h2d3a13d_1    conda-forge
readline                  8.2                  h8fc344f_1    conda-forge
regex                     2024.11.6       py310ha766c32_0    conda-forge
requests                  2.32.3             pyhd8ed1ab_1    conda-forge
s2n                       1.5.9                h636ded1_0    conda-forge
safetensors               0.4.5           py310h04a307d_0    conda-forge
setuptools                75.6.0             pyhff2d567_1    conda-forge
six                       1.16.0             pyhd8ed1ab_1    conda-forge
sleef                     3.7                  h8fb0607_2    conda-forge
snappy                    1.2.1                h1088aeb_0    conda-forge
sympy                     1.13.3           pyh2585a3b_104    conda-forge
tk                        8.6.13               h194ca79_0    conda-forge
tokenizers                0.20.4          py310h7f35fa6_0    conda-forge
torchvision               0.20.1          cuda126py310h2c728b7_0    conda-forge
tqdm                      4.67.1             pyhd8ed1ab_0    conda-forge
transformers              4.46.3             pyhd8ed1ab_0    conda-forge
typing-extensions         4.12.2               hd8ed1ab_1    conda-forge
typing_extensions         4.12.2             pyha770c72_1    conda-forge
tzdata                    2024b                hc8b5060_0    conda-forge
urllib3                   2.2.3              pyhd8ed1ab_1    conda-forge
wheel                     0.45.1             pyhd8ed1ab_1    conda-forge
xorg-libxau               1.0.11               h86ecc28_1    conda-forge
xorg-libxdmcp             1.1.5                h57736b2_0    conda-forge
xxhash                    0.8.2                h31becfc_0    conda-forge
xz                        5.2.6                h9cdd2b7_0    conda-forge
yaml                      0.2.5                hf897c2e_2    conda-forge
yarl                      1.18.0          py310ha766c32_0    conda-forge
zstandard                 0.23.0          py310h6a57b22_1    conda-forge
zstd                      1.5.6                h02f22dd_0    conda-forge
```

### Environment info

```shell
active environment : pytorch_env
    active env location : /home/brics/akawafi1.brics/miniforge3/envs/pytorch_env
            shell level : 2
       user config file : /home/brics/akawafi1.brics/.condarc
 populated config files : /home/brics/akawafi1.brics/miniforge3/.condarc
          conda version : 24.9.2
    conda-build version : not installed
         python version : 3.10.2.final.0
                 solver : libmamba (default)
       virtual packages : __archspec=1=neoverse_v2
                          __conda=24.9.2=0
                          __cuda=12.2=0
                          __glibc=2.31=0
                          __linux=5.14.21=0
                          __unix=0=0
       base environment : /home/brics/akawafi1.brics/miniforge3  (writable)
      conda av data dir : /home/brics/akawafi1.brics/miniforge3/etc/conda
  conda av metadata url : None
           channel URLs : https://conda.anaconda.org/conda-forge/linux-aarch64
                          https://conda.anaconda.org/conda-forge/noarch
          package cache : /home/brics/akawafi1.brics/miniforge3/pkgs
                          /home/brics/akawafi1.brics/.conda/pkgs
       envs directories : /home/brics/akawafi1.brics/miniforge3/envs
                          /home/brics/akawafi1.brics/.conda/envs
               platform : linux-aarch64
             user-agent : conda/24.9.2 requests/2.31.0 CPython/3.10.2 Linux/5.14.21-150500.55.31_13.0.53-cray_shasta_c_64k sles/15.5 glibc/2.31 solver/libmamba conda-libmamba-solver/24.1.0 libmambapy/1.5.8
                UID:GID : 1483800130:1483800130
             netrc file : None
           offline mode : False
```

**Comment by wahabk** [comment]
I fixed this issue by adding `dist.barrier()` before starting my processes.

Similar to this multi-gpu timeout: https://github.com/huggingface/accelerate/issues/314

**Comment by h-vetinari** [comment]
@conda-forge/nccl JFYI about problems in `checkForNCCLErrorsInternal` in a multi-GPU setup.

CC @conda-forge/cuda

**Comment by jakirkham** [comment]
Thanks for reporting Wahab! 🙏

So in terms of NCCL, we only package the dynamic library and [we test the static library is not shipped]( https://github.com/conda-forge/nccl-feedstock/blob/ed24dca9ce35fdac931939b773c616638299a9b3/recipe/meta.yaml#L42 )

As the PyTorch uses our NCCL package here, they would need to dynamically link as well. Also this means the PyTorch package is pulling in the NCCL package, which the `conda list` above seems to indicate

Since it sounds like you supply your own NCCL, it could make sense to add a Conda package in your own channel that either contains your NCCL library or configures Conda packages to find your NCCL library through some mechanism (symlink, environment variable, etc.). Then users could add this channel with higher priority than conda-forge to ensure your NCCL is gotten (instead of something else)

Please let us know what you think of this approach. Happy to chat further as needed
